name: 'Repo Lockdown'

on:
  issues:
    types: opened
  pull_request_target:
    types: opened

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v4
        with:
          github-token: ${{ github.token }}
          issue-comment: |
              Thank you for opening an issue however,
              PiVPN is in read-only mode, issues are not accepted.
              More info is available in the README.
              Github discussions is still available if you want help from community.

          pr-comment: |
              Thank you for your pull request however,
              PiVPN is in read-only mode, pull requests are not accepted.
              More info is available in the README.
              Github discussions is still available if you want help from community.

